### ISSUE TITLE
【小技巧】css3遮罩实现png图片变色

### ISSUE THREAD

**Issue by huatten** [MrTenger/myNote#139]
需求：将黑色图标变成红色图标。

![image](https://github.com/huatten/myNote/assets/10781715/ce2e9d25-dd54-4ec2-9e1e-809c3a4d2ae7)

原理：
CSS的mask是基于透明度实现遮罩层效果的，也就是实色区域显示，透明区域隐藏。因此只需要把目标图标的颜色作为背景色，然后将原始图标作为遮罩图片，即可实现效果。缺点是IE不支持。

代码：
```css
<span class="icon"></span>
.icon{
    display: inline-block;
    width: 64px;
    height: 64px;
    -webkit-mask: url("happy.png") no-repeat;
    mask: url("happy.png") no-repeat;
    -webkit-mask-size: 100% 100%;
    mask-size: 100% 100%;
}
```
