### ISSUE TITLE
【记一次贴吧面试】- padding实现图片的高度自适应

### ISSUE THREAD

**Issue by MrTenger** [MrTenger/myNote#3]
#### 1. 需求场景
我们在实现的时候，需要轮播图充满我们的轮播区域，通常我们的做法是banner设置固定宽高,然后超出隐藏，img设置max-width:100%，这样虽然能实现充满轮播区域，可是我们会发现，虽然宽度自适应了，高度并没有自适应，有时候我们会发现纵向上图片底部不见了，因为如果图片太高，当图片宽度100% 自适应的时候，高度也会按照宽度自适应的比例进行自适应(缩小或放大)，此时高度超出banner区域被隐藏了，视觉上会造成图片丢失的感觉。

#### 2. 涉及知识点
 在默认的水平文档流方向下，CSS margin和padding属性的垂直方向的百分比值都是相对于 ```宽度``` 计算的，所以不管是 padding-left 和 padding-right 还是 padding-top 和 padding-bottom 都是基于父元素宽度的百分比。

#### 3. 思路
首先，我们需要计算出图片的宽高比例，本文案例中使用了一张 750x366 的图片，宽高比就是 ```750 / 366 = 2.05```，假设将图片父容器宽度设置为100%，那么图片的高度就是 ```100% / 2.05 = 48.8%```，所以图片的高度按比例缩放就是 基于父元素宽度的 ```48.8%``。

举例代码：
```css
.contain{
   max-width: 750px;
   margin: 10px auto;
   overflow: hidden;
}
.banner{
   width: 100%;
   padding-top: 48.8%;  //当当当！划重点！
   position: relative;
}
.contain img{
   position: absolute;
   top: 0;
   left: 0;
   width: 100%;
   height: 100%;
}
```
页面结构
```html
 <div class="contain">
     <div class="banner"><img src="./image/banner.jpg" alt="banner"/></div>
 </div>
```
