### ISSUE TITLE
【兼容性】iPhone下input设置disabled属性后字体颜色修改

### ISSUE THREAD

**Issue by MrTenger** [MrTenger/myNote#5]
最近在做项目的时候发现，将input或textarea设置为disabled后，在iphone手机上样式将被覆写，解决方案如下：
```css
input:disabled, textarea:diabled {
    -webkit-text-fill-color: #ccc;
    opacity: 1;
    color: #ccc;
}
```
以上样式将覆盖其系统默认设置的值，能够实现android和ios的兼容性，使其表现一致。否则以上样式在iPhone下面表现为白色，安卓下为灰色。其中，`-webkit-text-fill-color` 是用来做填充色使用的，如果有设置这个值，则color属性将不生效。
